# name: Label PRs

# on:
#   pull_request:
#     types: [closed, edited]
    

# jobs:
#   build:

#     runs-on: ubuntu-latest
#     if: github.event.pull_request.merged == true
#     steps:
#       - uses: Rashmitha-ravichandran/labeler@master
#         env:
#           GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Hello world action step
        uses: ./.github/labeler
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"